language: rust

rust:
  - stable
  - beta
  - nightly

env:
  - FEATURES=""
  - FEATURES=native_lib

matrix:
  allow_failures:
    - rust: nightly

# Only cache cargo subcommand binaries and built Wayland libs.
# We need to cache the whole .cargo directory to keep the .crates.toml file.
cache:
  directories:
    - "$HOME/install"
    - "$HOME/.cargo"

# Don't cache the cargo registry.
before_cache:
  - rm -rf "$HOME/.cargo/registry"

install:
  - if [ -n "$FEATURES" ]; then
      .travis/install_wayland_libs.sh "1.15.0";
      export LD_LIBRARY_PATH="$HOME/install/lib:$LD_LIBRARY_PATH";
    fi

script:
  - cargo build --features "$FEATURES" --verbose
  - cargo test --features "$FEATURES" --verbose

  - if [ -z "$FEATURES" ]; then
      cargo doc --verbose;
      cp .travis/index.html target/doc;
    fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: target/doc
  on:
    branch: master
    rust: stable
    condition: "-z $FEATURES"
